In [ ]:
print("Welcome to NLP....")

In [ ]:
import re

In [ ]:
details_one = "This is my mobile_numbers and email_id: (012)-345-6789, 7418529630, abc@yahoo.com, ab_1_CD@gmail.com"

In [ ]:
'''
Source: https://regex101.com/

\d is a single number
\d{x} is a group of characters. x = 1,2,3.....

[a-z] is a single character
[a-z]* is a group of characters

 '''
pattern_mobile_number = ' \d{10}|\(\d{3}\)-\d{3}-\d{4}'
pattern_email_id = '[a-zA-Z0-9_]*@[a-zA-Z0-9_]*\.[a-z]*'
match_mobile_number = re.findall(pattern_mobile_number, details_one)
match_email_id = re.findall(pattern_email_id, details_one)
print(match_mobile_number)
print(match_email_id)

In [ ]:
'''
[^\d] - except digit
Question: order_number is 567. I want only 567 to be printed as an output. How ?
Answer: order_number[^\d]*([\d]*) - You need to place () so that only number gets printed.

'''
chat_one = "My product number is 123456789 and the other product # is 987654321"

pattern_product_number = "product[^\d]*([\d]*)"

match_product_number = re.findall(pattern_product_number, chat_one)
print(match_product_number)


In [ ]:
'''Information Extraction'''

pattern_age = 'age ([\d]+)'
pattern_born = 'Born(.*)\n'
pattern_dob = 'Born.*\n(.*)\(age'
text ='''
Born	             TejaswiSaiKumar
                   15 July 1997 (age 26)
                   Guntur, Andhra Pradesh, India
Other names        Teja
Occupation	       Student
Years active       1997-till date
'''

match_born = re.findall(pattern_born, text)
match_age = re.findall(pattern_age, text)
match_dob = re.findall(pattern_dob, text)

print(match_born)
'Add strip() to avoid spaces'
print(match_born[0].strip(), "\n")

print(match_age, "\n")
print(match_dob)
print(match_dob[0].strip())

In [ ]:
'''spaCy and NLTK

'''
import spacy
import nltk

In [ ]:
# nlp = spacy.blank("en")
# nlp = spacy.load("en_core_web_sm")

In [ ]:
nlp.pipe_names

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
'''Sentence tokenization
Using object-oriented programming'''


document = nlp("Mr. Tej loves samosa. He also likes garlic naan.")

for sentence in document.sents:
  print(sentence)

In [ ]:
'''Word tokeniation
Using object-oriented programming'''

for sentence in document.sents:
  for word in sentence:
    print(word)

In [ ]:
'''NLTK'''

# import nltk
nltk.download('punkt')

In [ ]:
from nltk.tokenize import sent_tokenize

sent_tokenize("Mr. Tej loves samosa. He also likes garlic naan.")

In [ ]:
from nltk.tokenize import word_tokenize
word_tokenize("Mr. Tej loves samosa. He also likes garlic naan.")

In [ ]:
nlp = spacy.blank("en")
print(type(nlp), "\n")

doc = nlp("Mr. Tej loves samosa. He also likes garlic naan. The cost of these two were $10.00")
token_like_num = doc[15]
print(token_like_num)
print(type(token_like_num))
print(token_like_num.like_num)
print("--------------------------------------------------")
token_like_currency = doc[17]
print(token_like_currency)
print(type(token_like_currency))
print(token_like_currency.is_currency)
print("--------------------------------------------------")
for tokens in doc:
  print(tokens)

In [ ]:
for token in doc:
  print(token, "---->", "index:", token.i, "======>"
        "is_alpha:", token.is_alpha,
        "is_punct:", token.is_punct,
        "is_currency:", token.is_currency)

In [ ]:
print(doc[5], "\n")
span = doc[1:4]
print(span, "\n")
print(type(span), "\n")
print(doc[-6])

In [ ]:
doc = nlp('''"Let's go to N.Y.!"''')
for tokens in doc:
  print(tokens)

In [ ]:
with open('fiu_ms_students.txt') as file:
  text = file.readlines()
text

In [ ]:
text = ' '.join(text)
text

In [ ]:
doc = nlp(text)
email_id = []
others = []
websites = []
for token in doc:
  if token.like_email:
    email_id.append(token)
  elif token.like_url:
    websites.append(token)
  else:
    others.append(token)
print(email_id)
print(websites)
print(others)



In [ ]:
'''
special cases are not allowed to modify the text
'''
from spacy.symbols import ORTH

doc1 = nlp("gimme one sprite and manchuria")
nlp.tokenizer.add_special_case("gimme",
                               [{ORTH: "gim"}, {ORTH: "me"}])

for token in doc1:
  print(token)

In [ ]:
doc = nlp("Mr. Tej loves samosa. He also likes garlic naan. The cost of these two were $10.00")

for sentence in doc.sents:
  print(sentence)

In [ ]:
nlp.pipe_names

In [ ]:
nlp.add_pipe('sentencizer')

In [ ]:
nlp.pipe_names

In [ ]:
doc = nlp("Mr. Tej loves samosa. He also likes garlic naan. The cost of these two were $10.00")

for sentence in doc.sents:
  print(sentence)

In [ ]:
# Exercise: Extract all the money transactions from below sentence along with currency

transactions = "Tony gave two $ to Peter, Bruce gave 500 € to Steve"
doc = nlp(transactions)
for token in doc:
  print(token)

In [ ]:
if token.like_num and doc[token.i+1].is_currency:
  print(token.text, doc[token.i+1].text)

In [ ]:
nlp = spacy.blank("en")
doc = nlp("Teja ate 10.69$ large pizza. He eat all eight slices at once")

# for token in doc:
#   print(token)

for token in doc:
  print(token, "|", token.pos_, "|", token.lemma_)

In [ ]:
'''
pos_ is a part of speech (tagger component in a pipieline)
lemma_ is lemmatization (Lemmatizer component in a pipieline)
'''
nlp = spacy.load("en_core_web_sm")

doc = nlp("Teja ate 10.69$ large pizza. He eat all eight slices at once")

for token in doc:
  print(token, "|", token.pos_, "|", token.lemma_)

In [ ]:
doc = nlp("Tesla Inc completed their purchase of Twitter for $44 billion")

for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

In [ ]:
from spacy import displacy

displacy.render(doc, style = "ent")

In [ ]:
'''
Adding a custom component to a blank pipeline
Finally printing the entities for a given text
'''
nlp = spacy.blank("en")
doc = nlp("Teja ate 10.69$ large pizza. He eat all eight slices at once")

for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

In [ ]:
nlp.pipe_names

In [ ]:
components_pipeline = spacy.load("en_core_web_sm")

empty_pipeline = spacy.blank("en")

empty_pipeline.add_pipe("ner", source=components_pipeline)
empty_pipeline.pipe_names

In [ ]:
doc = empty_pipeline("Tesla Inc completed their purchase of Twitter for $44 billion")

for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

In [ ]:
from nltk import PorterStemmer

port_stemmer = PorterStemmer()

In [ ]:
actual_words = ['eating', 'palying', 'jumping', 'eats', 'ability', 'ate', 'adjustable']

for base_words in actual_words:
  print(base_words, "|", port_stemmer.stem(base_words))

In [ ]:
'''
lemma - unique hash identifier of the base word
'''
nlp = spacy.load("en_core_web_sm")   #trained english model with a fixed vocabulary
doc = nlp("Tej eats pizza. He feels better now after eating food")

for token in doc:
  print(token, "|", token.lemma_, "|", token.lemma)

Tej | tej | 14454720703979291041
eats | eat | 9837207709914848172
pizza | pizza | 13450285337346246112
. | . | 12646065887601541794
He | he | 1655312771067108281
feels | feel | 5741770584995928333
better | well | 4525988469032889948
now | now | 17157488710739566268
after | after | 13428508259213873547
eating | eat | 9837207709914848172
food | food | 18057327756930201825


In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
'''Set attribute rule'''

attributeRuler = nlp.get_pipe("attribute_ruler")

attributeRuler.add([[{"TEXT": "Teja"}], [{"TEXT":"Tejaswi"}]], {"LEMMA": "TSK"})

doc = nlp("Tejaswi eats pizza. Teja feels better now after eating food")

for token in doc:
  print(token, "|", token.lemma_)

Tejaswi | TSK
eats | eat
pizza | pizza
. | .
Teja | TSK
feels | feel
better | well
now | now
after | after
eating | eat
food | food


Parts of Speech

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
doc = nlp("Tej went to United States of America in the year 2022. The reason is to pursue his higher education")

for token in doc:
  print(token, "|", token.pos_, "|", spacy.explain(token.pos_), "|", spacy.explain(token.tag_))

Tej | PROPN | proper noun | noun, proper singular
went | VERB | verb | verb, past tense
to | ADP | adposition | conjunction, subordinating or preposition
United | PROPN | proper noun | noun, proper singular
States | PROPN | proper noun | noun, proper singular
of | ADP | adposition | conjunction, subordinating or preposition
America | PROPN | proper noun | noun, proper singular
in | ADP | adposition | conjunction, subordinating or preposition
the | DET | determiner | determiner
year | NOUN | noun | noun, singular or mass
2022 | NUM | numeral | cardinal number
. | PUNCT | punctuation | punctuation mark, sentence closer
The | DET | determiner | determiner
reason | NOUN | noun | noun, singular or mass
is | AUX | auxiliary | verb, 3rd person singular present
to | PART | particle | infinitival "to"
pursue | VERB | verb | verb, base form
his | PRON | pronoun | pronoun, possessive
higher | ADJ | adjective | adjective, comparative
education | NOUN | noun | noun, singular or mass


In [ ]:
microsft_earnings = """Microsoft Corp. today announced the following results for the quarter ended December 31, 2023, as compared to the corresponding period of last fiscal year: Revenue was $62.0 billion and increased 18% (up 16% in constant currency). Operating income was $27.0 billion and increased 33%, and increased 25% non-GAAP (up 23% in constant currency). Net income was $21.9 billion and increased 33%, and increased 26% non-GAAP (up 23% in constant currency). Diluted earnings per share was $2.93 and increased 33%, and increased 26% non-GAAP (up 23% in constant currency). Microsoft completed the acquisition of Activision Blizzard, Inc. (“Activision”) on October 13, 2023. Financial results from the acquired business are reported in the More Personal Computing segment."""

doc = nlp(microsft_earnings)

for token in doc:
  print(token, "|", token.pos_, "|", spacy.explain(token.pos_))

Microsoft | PROPN | proper noun
Corp. | PROPN | proper noun
today | NOUN | noun
announced | VERB | verb
the | DET | determiner
following | VERB | verb
results | NOUN | noun
for | ADP | adposition
the | DET | determiner
quarter | NOUN | noun
ended | VERB | verb
December | PROPN | proper noun
31 | NUM | numeral
, | PUNCT | punctuation
2023 | NUM | numeral
, | PUNCT | punctuation
as | SCONJ | subordinating conjunction
compared | VERB | verb
to | ADP | adposition
the | DET | determiner
corresponding | ADJ | adjective
period | NOUN | noun
of | ADP | adposition
last | ADJ | adjective
fiscal | ADJ | adjective
year | NOUN | noun
: | PUNCT | punctuation
Revenue | NOUN | noun
was | AUX | auxiliary
$ | SYM | symbol
62.0 | NUM | numeral
billion | NUM | numeral
and | CCONJ | coordinating conjunction
increased | VERB | verb
18 | NUM | numeral
% | NOUN | noun
( | PUNCT | punctuation
up | ADV | adverb
16 | NUM | numeral
% | NOUN | noun
in | ADP | adposition
constant | ADJ | adjective
currency | NOUN |

In [ ]:
'''#Method:1'''
filtered_tokens = []

for token in doc:
  if token.pos_ not in ["PUNCT"]:
    print(token, "|", token.pos_, "|", spacy.explain(token.pos_))

Microsoft | PROPN | proper noun
Corp. | PROPN | proper noun
today | NOUN | noun
announced | VERB | verb
the | DET | determiner
following | VERB | verb
results | NOUN | noun
for | ADP | adposition
the | DET | determiner
quarter | NOUN | noun
ended | VERB | verb
December | PROPN | proper noun
31 | NUM | numeral
2023 | NUM | numeral
as | SCONJ | subordinating conjunction
compared | VERB | verb
to | ADP | adposition
the | DET | determiner
corresponding | ADJ | adjective
period | NOUN | noun
of | ADP | adposition
last | ADJ | adjective
fiscal | ADJ | adjective
year | NOUN | noun
Revenue | NOUN | noun
was | AUX | auxiliary
$ | SYM | symbol
62.0 | NUM | numeral
billion | NUM | numeral
and | CCONJ | coordinating conjunction
increased | VERB | verb
18 | NUM | numeral
% | NOUN | noun
up | ADV | adverb
16 | NUM | numeral
% | NOUN | noun
in | ADP | adposition
constant | ADJ | adjective
currency | NOUN | noun
Operating | VERB | verb
income | NOUN | noun
was | AUX | auxiliary
$ | SYM | symbol
27.0 |

In [ ]:
'''Method:2'''

filtered_tokens = []

for token in doc:
  if token.pos_ not in ["PUNCT"]:
    filtered_tokens.append(token)

filtered_tokens

[Microsoft,
 Corp.,
 today,
 announced,
 the,
 following,
 results,
 for,
 the,
 quarter,
 ended,
 December,
 31,
 2023,
 as,
 compared,
 to,
 the,
 corresponding,
 period,
 of,
 last,
 fiscal,
 year,
 Revenue,
 was,
 $,
 62.0,
 billion,
 and,
 increased,
 18,
 %,
 up,
 16,
 %,
 in,
 constant,
 currency,
 Operating,
 income,
 was,
 $,
 27.0,
 billion,
 and,
 increased,
 33,
 %,
 and,
 increased,
 25,
 %,
 non,
 -,
 GAAP,
 up,
 23,
 %,
 in,
 constant,
 currency,
 Net,
 income,
 was,
 $,
 21.9,
 billion,
 and,
 increased,
 33,
 %,
 and,
 increased,
 26,
 %,
 non,
 -,
 GAAP,
 up,
 23,
 %,
 in,
 constant,
 currency,
 Diluted,
 earnings,
 per,
 share,
 was,
 $,
 2.93,
 and,
 increased,
 33,
 %,
 and,
 increased,
 26,
 %,
 non,
 -,
 GAAP,
 up,
 23,
 %,
 in,
 constant,
 currency,
 Microsoft,
 completed,
 the,
 acquisition,
 of,
 Activision,
 Blizzard,
 Inc.,
 Activision,
 on,
 October,
 13,
 2023,
 Financial,
 results,
 from,
 the,
 acquired,
 business,
 are,
 reported,
 in,
 the,
 More,
 Per

In [ ]:
'''Count the number of nouns, verbs and so on
To do so: coutby() '''

count = doc.count_by(spacy.attrs.)
print(count)
print(count.items())

{96: 11, 92: 38, 100: 15, 90: 6, 85: 12, 93: 22, 97: 26, 98: 1, 84: 11, 87: 5, 99: 4, 89: 7, 86: 4}
dict_items([(96, 11), (92, 38), (100, 15), (90, 6), (85, 12), (93, 22), (97, 26), (98, 1), (84, 11), (87, 5), (99, 4), (89, 7), (86, 4)])


In [ ]:
doc.vocab[96].text

'PROPN'

In [ ]:
for key, value in count.items():
  print(doc.vocab[key].text, "|", value)

PROPN | 11
NOUN | 38
VERB | 15
DET | 6
ADP | 12
NUM | 22
PUNCT | 26
SCONJ | 1
ADJ | 11
AUX | 5
SYM | 4
CCONJ | 7
ADV | 4


Named Entity Recognition

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [ ]:
doc = nlp("Tesla bought Twitter Inc for $45 billions.")

for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

Tesla | ORG | Companies, agencies, institutions, etc.
Twitter Inc | ORG | Companies, agencies, institutions, etc.
$45 billions | MONEY | Monetary values, including unit


In [ ]:
from spacy import displacy

displacy.render(doc, style = "ent")

In [ ]:
doc = nlp("Michael bloomberg founded Bloomberg in 1982.")

for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

Michael bloomberg | PERSON | People, including fictional
Bloomberg | ORG | Companies, agencies, institutions, etc.
1982 | DATE | Absolute or relative dates or periods


In [ ]:
from spacy import displacy

displacy.render(doc, style = "ent")

In [ ]:
doc = nlp("Google launched Gmail in 2005")
for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

Google | ORG | Companies, agencies, institutions, etc.
Gmail | PERSON | People, including fictional
2005 | DATE | Absolute or relative dates or periods


In [ ]:
from spacy import displacy

displacy.render(doc, style = "ent")

In [ ]:
from spacy.tokens import Span
s1 = Span(doc, 2, 3, label = "ORG")

doc.set_ents([s1], default="unmodified")

In [ ]:
for ent in doc.ents:
  print(ent.text, "|", ent.label_, "|", spacy.explain(ent.label_))

Google | ORG | Companies, agencies, institutions, etc.
Gmail | ORG | Companies, agencies, institutions, etc.
2005 | DATE | Absolute or relative dates or periods


In [ ]:
from spacy import displacy

displacy.render(doc, style = "ent")

In [ ]:
'''Feature Engineering:
1. It is the process of extracting features from raw data. In NLP, we call it as "Text Representation"
2. Representing text as a vector is known as "Feature space model".
3. Various approches of doing text representation in NLP - One hot encoding, Bag of words, TF-IDF, Word embeddings

Question: How do you extract features from text ?
Answer: One way could be - We can ask couple of questions i.e, handcrafted features
represent it as a 'feature vector'
'''



In [ ]:
'''Text representation using 'bag of words'
'''

import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/spam.csv')
df.head(10)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [ ]:
#Count how many 'hams' and 'spam' are present in the dataset

print(df.Category.value_counts(), "\n")
print("The shape of the dataset is:", df.shape)

Category
ham     4825
spam     747
Name: count, dtype: int64 

The shape of the dataset is: (5572, 4)


In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df

Category                                            Message  ham/spam  \
0         ham  Go until jurong point, crazy.. Available only ...         0   
1         ham                      Ok lar... Joking wif u oni...         0   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...         1   
3         ham  U dun say so early hor... U c already then say...         0   
4         ham  Nah I don't think he goes to usf, he lives aro...         0   
...       ...                                                ...       ...   
5567     spam  This is the 2nd time we have tried 2 contact u...         1   
5568      ham               Will ü b going to esplanade fr home?         0   
5569      ham  Pity, * was in mood for that. So...any other s...         0   
5570      ham  The guy did some bitching but I acted like i'd...         0   
5571      ham                         Rofl. Its true to its name         0   

      spam  
0        0  
1        0  
2        1  
3        0  
4        0  
...    ...  
5567     1  
5568     0  
5569     0  
5570     0  
5571     0  

[5572 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
X_train[:3]

3074           Somebody should go to andros and steal ice
4866             I'm really sorry I lit your hair on fire
2532    What's happening with you. Have you gotten a j...
Name: Message, dtype: object

In [ ]:
X_train[:3][2532]

"What's happening with you. Have you gotten a job and have you begun registration for permanent residency"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_train_cv = cv.fit_transform(X_train)
X_train_cv

<4457x7812 sparse matrix of type '<class 'numpy.int64'>'
	with 59397 stored elements in Compressed Sparse Row format>

In [ ]:
cv.get_feature_names_out()[964]

'and'

In [ ]:
X_train_cv_np_array = X_train_cv.toarray()
X_train_cv_np_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv_np_array[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#I would like to know at which indexes the values are not zero

np.where(X_train_cv_np_array[0]!= 0)

(array([ 964,  969, 3189, 3615, 6168, 6350, 6517, 6997]),)

In [ ]:
X_train[:4][3074]

'Somebody should go to andros and steal ice'

In [ ]:
X_train_cv_np_array[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = cv.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       975
           1       0.98      0.94      0.96       140

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
emails = ['Your passport has been shipped', 'Hurry up ! Claim your $10,000 reward card for free']
emails_count = cv.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
# The other way of doing it was creating a 'sklearn pipeline'

from sklearn.pipeline import Pipeline

clf = Pipeline([("Vectorizer", CountVectorizer()), ("nb", MultinomialNB())])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('Vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       975
           1       0.98      0.94      0.96       140

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
'''Stop words'''

import spacy
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
# Looks at all the stop words that are available in english model
print(len(STOP_WORDS), "\n")
STOP_WORDS

326 



{"'d",
 "'ll",
 "'m",
 "'re",
 "'s",
 "'ve",
 'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'both',
 'bottom',
 'but',
 'by',
 'ca',
 'call',
 'can',
 'cannot',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'four',
 'from',
 'fron

In [ ]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("Nandamuri Taraka Rama Rao Jr, also known as Tarak, is an Indian actor who primarily works in Telugu cinema. One of the highest paid Telugu film actors. Rama Rao has won several accolades, including two Filmfare Awards, two state Nandi Awards, and four CineMAA Awards. Since 2012, he has been featured in Forbes India's Celebrity 100 list.")

for token in doc:
  if not token.is_stop and not token.is_punct:
    print(token)

Nandamuri
Taraka
Rama
Rao
Jr
known
Tarak
Indian
actor
primarily
works
Telugu
cinema
highest
paid
Telugu
film
actors
Rama
Rao
won
accolades
including
Filmfare
Awards
state
Nandi
Awards
CineMAA
Awards
2012
featured
Forbes
India
Celebrity
100
list


In [ ]:
import pandas as pd
df = pd.read_json('/content/combined.json', lines = True)
print(df.shape, "\n")
df.head(10)

(13087, 6) 



id                                              title  \
0     None       Convicted Bomb Plotter Sentenced to 30 Years   
1  12-919   $1 Million in Restitution Payments Announced t...   
2  11-1002  $1 Million Settlement Reached for Natural Reso...   
3   10-015  10 Las Vegas Men Indicted \r\nfor Falsifying V...   
4   18-898  $100 Million Settlement Will Speed Cleanup Wor...   
5     None  105 Individuals Indicted for Violating the RIC...   
6   14-032  12th Former Officer at Roxbury Correctional In...   
7  14-1412  14 Indicted in Connection with New England Com...   
8   14-849  14 Individuals Charged with Trafficking Identi...   
9   15-089  15th Member of Washington, D.C.-Based Identity...   

                                            contents  \
0  PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...   
1    WASHINGTON – North Carolina’s Waccamaw River...   
2        BOSTON– A $1-million settlement has been...   
3    WASHINGTON—A federal grand jury in Las Vegas...   
4  The U.S. Department of Justice, the U.S. Envir...   
5  A nine count federal indictment was unsealed t...   
6  Michael Morgan, formerly an officer at Roxbury...   
7  A 131-count criminal indictment was unsealed t...   
8    Fourteen  individuals were charged in three ...   
9  Defendant Admits To Targeting Parents Of Hospi...   

                        date                 topics  \
0  2014-10-01T00:00:00-04:00                     []   
1  2012-07-25T00:00:00-04:00                     []   
2  2011-08-03T00:00:00-04:00                     []   
3  2010-01-08T00:00:00-05:00                     []   
4  2018-07-09T00:00:00-04:00          [Environment]   
5  2015-07-22T00:00:00-04:00                     []   
6  2014-01-10T00:00:00-05:00                     []   
7  2014-12-17T00:00:00-05:00  [Consumer Protection]   
8  2014-08-12T00:00:00-04:00                     []   
9  2015-01-23T00:00:00-05:00                     []   

                                          components  
0                 [National Security Division (NSD)]  
1       [Environment and Natural Resources Division]  
2       [Environment and Natural Resources Division]  
3       [Environment and Natural Resources Division]  
4       [Environment and Natural Resources Division]  
5                               [USAO - Puerto Rico]  
6  [Civil Rights Division, Civil Rights - Crimina...  
7                                   [Civil Division]  
8                                [Criminal Division]  
9                                [Criminal Division]

In [ ]:
# The use case is "We need to auto extract all the topics"

df = df[df["topics"].str.len() != 0]
print(df.shape, "\n")
df.head(10)

(4688, 6) 



id                                              title  \
4    18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7   14-1412  14 Indicted in Connection with New England Com...   
19  17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22  15-1562  21st Century Oncology to Pay $19.75 Million to...   
23  17-1404  21st Century Oncology to Pay $26 Million to Se...   
26   18-961   24 Defendants Sentenced in Multimillion Dolla...   
27   12-306  $25 Billion Mortgage Servicing Agreement Filed...   
29  17-1182  30 Members and Associates of The "Nine Trey Ga...   
30  15-1560  32 Hospitals to Pay U.S. More Than $28 Million...   
32     None  34 Individuals Facing Federal and Tribal Charg...   

                                             contents  \
4   The U.S. Department of Justice, the U.S. Envir...   
7   A 131-count criminal indictment was unsealed t...   
19  The United States Attorney’s Office for the Mi...   
22  21st Century Oncology LLC, has agreed to pay $...   
23  21st Century Oncology Inc. and certain of its ...   
26  Twenty-one members of a massive India-based fr...   
27  View the court documents.  WASHINGTON – The Ju...   
29  Federal agents have arrested 17 members and as...   
30  Thirty-two hospitals located throughout 15 sta...   
32  Thirty-four individuals are facing federal and...   

                         date  \
4   2018-07-09T00:00:00-04:00   
7   2014-12-17T00:00:00-05:00   
19  2017-12-14T00:00:00-05:00   
22  2015-12-18T00:00:00-05:00   
23  2017-12-12T00:00:00-05:00   
26  2018-07-20T00:00:00-04:00   
27  2012-03-12T00:00:00-04:00   
29  2017-10-23T00:00:00-04:00   
30  2015-12-18T00:00:00-05:00   
32  2015-12-14T00:00:00-05:00   

                                               topics  \
4                                       [Environment]   
7                               [Consumer Protection]   
19                                      [Environment]   
22              [False Claims Act, Health Care Fraud]   
23              [Health Care Fraud, False Claims Act]   
26               [Consumer Protection, Elder Justice]   
27                   [Consumer Protection, StopFraud]   
29                                          [Opioids]   
30              [False Claims Act, Health Care Fraud]   
32  [Drug Trafficking, Indian Country Law and Just...   

                                           components  
4        [Environment and Natural Resources Division]  
7                                    [Civil Division]  
19  [Environment and Natural Resources Division, U...  
22                                   [Civil Division]  
23           [Civil Division, USAO - Florida, Middle]  
26        [Criminal Division, USAO - Texas, Southern]  
27         [Office of the Associate Attorney General]  
29      [Criminal Division, USAO - Georgia, Northern]  
30                                   [Civil Division]  
32                                [USAO - New Mexico]

In [ ]:
df = df.head(100)
print(df.shape, "\n")
df

(100, 6) 



id                                              title  \
4     18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7    14-1412  14 Indicted in Connection with New England Com...   
19   17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22   15-1562  21st Century Oncology to Pay $19.75 Million to...   
23   17-1404  21st Century Oncology to Pay $26 Million to Se...   
..       ...                                                ...   
316  15-1359  Alaska Plastic Surgeon Convicted of Wire Fraud...   
318   16-396  Alaska Plastic Surgeon Sentenced to Prison for...   
321   17-736  Alaskan Commercial Fishing Couple Charged with...   
322   18-717  Alaskan Husband And Wife Plead Guilty To Willf...   
324  16-1345        Alaskan Oncologist Indicted for Tax Evasion   

                                              contents  \
4    The U.S. Department of Justice, the U.S. Envir...   
7    A 131-count criminal indictment was unsealed t...   
19   The United States Attorney’s Office for the Mi...   
22   21st Century Oncology LLC, has agreed to pay $...   
23   21st Century Oncology Inc. and certain of its ...   
..                                                 ...   
316  Doctor Hid Millions in Secret Accounts in Pana...   
318  Defendant Concealed Bank Accounts in Panama an...   
321  An Alaskan couple was charged in federal court...   
322  A husband and wife pleaded guilty yesterday to...   
324  A resident of Big Lake, Alaska was indicted on...   

                          date                                 topics  \
4    2018-07-09T00:00:00-04:00                          [Environment]   
7    2014-12-17T00:00:00-05:00                  [Consumer Protection]   
19   2017-12-14T00:00:00-05:00                          [Environment]   
22   2015-12-18T00:00:00-05:00  [False Claims Act, Health Care Fraud]   
23   2017-12-12T00:00:00-05:00  [Health Care Fraud, False Claims Act]   
..                         ...                                    ...   
316  2015-11-04T00:00:00-05:00                                  [Tax]   
318  2016-04-04T00:00:00-04:00                                  [Tax]   
321  2017-07-26T00:00:00-04:00                                  [Tax]   
322  2018-06-01T00:00:00-04:00                                  [Tax]   
324  2016-11-17T00:00:00-05:00                                  [Tax]   

                                            components  
4         [Environment and Natural Resources Division]  
7                                     [Civil Division]  
19   [Environment and Natural Resources Division, U...  
22                                    [Civil Division]  
23            [Civil Division, USAO - Florida, Middle]  
..                                                 ...  
316                                     [Tax Division]  
318                                     [Tax Division]  
321                      [Tax Division, USAO - Alaska]  
322                                     [Tax Division]  
324                                     [Tax Division]  

[100 rows x 6 columns]

In [ ]:
len(df['contents'].iloc[4])

5504

In [ ]:
#Function to remove stop words
def preprocess_no_stop_words(text):
  doc = nlp(text)

  no_StopWords = [token.text for token in doc if not token.is_stop and not token.is_punct]
  return " ".join(no_StopWords)

In [ ]:
df["contents_new"] = df["contents"].apply(preprocess_no_stop_words)
df.head(10)

id                                              title  \
4    18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7   14-1412  14 Indicted in Connection with New England Com...   
19  17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22  15-1562  21st Century Oncology to Pay $19.75 Million to...   
23  17-1404  21st Century Oncology to Pay $26 Million to Se...   
26   18-961   24 Defendants Sentenced in Multimillion Dolla...   
27   12-306  $25 Billion Mortgage Servicing Agreement Filed...   
29  17-1182  30 Members and Associates of The "Nine Trey Ga...   
30  15-1560  32 Hospitals to Pay U.S. More Than $28 Million...   
32     None  34 Individuals Facing Federal and Tribal Charg...   

                                             contents  \
4   The U.S. Department of Justice, the U.S. Envir...   
7   A 131-count criminal indictment was unsealed t...   
19  The United States Attorney’s Office for the Mi...   
22  21st Century Oncology LLC, has agreed to pay $...   
23  21st Century Oncology Inc. and certain of its ...   
26  Twenty-one members of a massive India-based fr...   
27  View the court documents.  WASHINGTON – The Ju...   
29  Federal agents have arrested 17 members and as...   
30  Thirty-two hospitals located throughout 15 sta...   
32  Thirty-four individuals are facing federal and...   

                         date  \
4   2018-07-09T00:00:00-04:00   
7   2014-12-17T00:00:00-05:00   
19  2017-12-14T00:00:00-05:00   
22  2015-12-18T00:00:00-05:00   
23  2017-12-12T00:00:00-05:00   
26  2018-07-20T00:00:00-04:00   
27  2012-03-12T00:00:00-04:00   
29  2017-10-23T00:00:00-04:00   
30  2015-12-18T00:00:00-05:00   
32  2015-12-14T00:00:00-05:00   

                                               topics  \
4                                       [Environment]   
7                               [Consumer Protection]   
19                                      [Environment]   
22              [False Claims Act, Health Care Fraud]   
23              [Health Care Fraud, False Claims Act]   
26               [Consumer Protection, Elder Justice]   
27                   [Consumer Protection, StopFraud]   
29                                          [Opioids]   
30              [False Claims Act, Health Care Fraud]   
32  [Drug Trafficking, Indian Country Law and Just...   

                                           components  \
4        [Environment and Natural Resources Division]   
7                                    [Civil Division]   
19  [Environment and Natural Resources Division, U...   
22                                   [Civil Division]   
23           [Civil Division, USAO - Florida, Middle]   
26        [Criminal Division, USAO - Texas, Southern]   
27         [Office of the Associate Attorney General]   
29      [Criminal Division, USAO - Georgia, Northern]   
30                                   [Civil Division]   
32                                [USAO - New Mexico]   

                                         contents_new  
4   U.S. Department Justice U.S. Environmental Pro...  
7   131 count criminal indictment unsealed today B...  
19  United States Attorney Office Middle District ...  
22  21st Century Oncology LLC agreed pay $ 19.75 m...  
23  21st Century Oncology Inc. certain subsidiarie...  
26  members massive India based fraud money launde...  
27  View court documents   WASHINGTON Justice Depa...  
29  Federal agents arrested 17 members associates ...  
30  Thirty hospitals located 15 states agreed pay ...  
32  Thirty individuals facing federal tribal drug ...

In [ ]:
len(df["contents"].iloc[4])

5504

In [ ]:
len(df["contents_new"].iloc[4])

4217

In [ ]:
'''Exercise'''

nlp = spacy.load("en_core_web_sm")

def preprocess_no_stop_words(text):
  doc = nlp(text)
  no_StopWords = [token.text for token in doc if not token.is_stop and not token.is_punct]
  return " ".join(no_StopWords)

#In spacy, declare 'not' is a not a stop word.
nlp.vocab['not'].is_stop = False

good= preprocess_no_stop_words("This is a good place")
bad = preprocess_no_stop_words("This is not a good place")

print(good)
print(bad)

good place
not good place


In [ ]:
'''Text representation using Bag of n-grams'''

from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(ngram_range = (2,2))
cv.fit(["HulkWanda is looking for a job"])
cv.vocabulary_


{'hulkwanda is': 1, 'is looking': 2, 'looking for': 3, 'for job': 0}

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
  doc = nlp(text)
  token_filter = []
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    token_filter.append(token.lemma_)

  return " ".join(token_filter)

In [ ]:
preprocess("Thor ate pizza")

'thor eat pizza'

In [ ]:
corpus = [
    'Tej ate pizza',
    'Suki is tall',
    'Sandy is eating pizza'
]

In [ ]:
corpus_new = [preprocess(text) for text in corpus]
corpus_new

['tej eat pizza', 'Suki tall', 'Sandy eat pizza']

In [ ]:
cv = CountVectorizer(ngram_range = (1,2))
cv.fit(corpus_new)
cv.vocabulary_


{'tej': 8,
 'eat': 0,
 'pizza': 2,
 'tej eat': 9,
 'eat pizza': 1,
 'suki': 5,
 'tall': 7,
 'suki tall': 6,
 'sandy': 3,
 'sandy eat': 4}

In [ ]:
cv.transform(["Tej eat pizza"]).toarray()

array([[1, 1, 1, 0, 0, 0, 0, 0, 1, 1]])

In [ ]:
cv.transform(["Krish eat dosa"]).toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
import pandas as pd
df = pd.read_json('/content/news_dataset.json')
print(df.shape, "\n")
df.head(10)

(12695, 2) 



text  category
0  Watching Schrödinger's Cat Die University of C...   SCIENCE
1     WATCH: Freaky Vortex Opens Up In Flooded Lake    SCIENCE
2  Entrepreneurs Today Don't Need a Big Budget to...  BUSINESS
3  These Roads Could Recharge Your Electric Car A...  BUSINESS
4  Civilian 'Guard' Fires Gun While 'Protecting' ...     CRIME
5  Trump Pays Penalty For Ethically Questionable ...  BUSINESS
6                          LIVE: Argentina vs. Iran     SPORTS
7  9 Tips for Making Your Blog Better in 2015 New...  BUSINESS
8  Man Arrested Over Threats To CNN:  'Fake News....     CRIME
9  Here's Why Coffee Makes You Have To Poop It hi...   SCIENCE

In [ ]:
df.category.value_counts()

category
BUSINESS    4254
SPORTS      4167
CRIME       2893
SCIENCE     1381
Name: count, dtype: int64

In [ ]:
minimum_samples = 1381
df_business = df[df.category == "BUSINESS"].sample(minimum_samples, random_state = 42)
df_sports = df[df.category == "SPORTS"].sample(minimum_samples, random_state = 42)
df_crime = df[df.category == "CRIME"].sample(minimum_samples, random_state = 42)
df_science = df[df.category == "SCIENCE"].sample(minimum_samples, random_state = 42)

In [ ]:
balanced_data = pd.concat([df_business, df_sports, df_crime, df_science], axis = 0)
balanced_data.category.value_counts()

category
BUSINESS    1381
SPORTS      1381
CRIME       1381
SCIENCE     1381
Name: count, dtype: int64

In [ ]:
target = {'BUSINESS': 0, 'SPORTS': 1, 'CRIME': 2, 'SCIENCE': 3}

balanced_data['category_number'] = balanced_data.category.map(target)

In [ ]:
balanced_data

text  category  \
594    How to Develop the Next Generation of Innovato...  BUSINESS   
3093   Madoff Victims' Payout Nears $7.2 Billion, Tru...  BUSINESS   
7447   Bay Area Floats 'Sanctuary In Transit Policy' ...  BUSINESS   
10388  Microsoft Agrees To Acquire LinkedIn For $26.2...  BUSINESS   
1782    Inside A Legal, Multibillion Dollar Weed Market   BUSINESS   
...                                                  ...       ...   
9924   A Call for Data Literacy If we care about youn...   SCIENCE   
10219  Here's What Happens When Someone Sneezes On An...   SCIENCE   
11884  Most People Don't See How Climate Change Is Af...   SCIENCE   
7854   Watch Octopuses Meet for Blind Date, Tricky Se...   SCIENCE   
10191  The World Of Science Has A Lot To Look Forward...   SCIENCE   

       category_number  
594                  0  
3093                 0  
7447                 0  
10388                0  
1782                 0  
...                ...  
9924                 3  
10219                3  
11884                3  
7854                 3  
10191                3  

[5524 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
'''
Stratify parameter will create a equal nube rof samples for train and test
'''

X_train, X_test, y_train, y_test = train_test_split(balanced_data.text, balanced_data.category_number, test_size= 0.2, random_state = 42, stratify = balanced_data.category_number)

In [ ]:
y_train.value_counts()

category_number
0    1105
3    1105
1    1105
2    1104
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

category_number
2    277
0    276
1    276
3    276
Name: count, dtype: int64

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report


In [ ]:
classifier = Pipeline([('vectorizer_bow,', CountVectorizer()), ('Multi NB', MultinomialNB())])
classifier

Pipeline(steps=[('vectorizer_bow,', CountVectorizer()),
                ('Multi NB', MultinomialNB())])

In [ ]:
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred

array([2, 2, 0, ..., 0, 1, 0])

In [ ]:
Classification_Report = classification_report(y_test, y_pred)
print(Classification_Report)

              precision    recall  f1-score   support

           0       0.78      0.92      0.84       276
           1       0.92      0.85      0.88       276
           2       0.91      0.89      0.90       277
           3       0.89      0.82      0.85       276

    accuracy                           0.87      1105
   macro avg       0.88      0.87      0.87      1105
weighted avg       0.88      0.87      0.87      1105



In [ ]:
classifier_n = Pipeline([('vectorizer_bow,', CountVectorizer(ngram_range=(1,2))), ('Multi NB', MultinomialNB())])
classifier_n

Pipeline(steps=[('vectorizer_bow,', CountVectorizer(ngram_range=(1, 2))),
                ('Multi NB', MultinomialNB())])

In [ ]:
classifier_n.fit(X_train, y_train)

y_pred = classifier_n.predict(X_test)
y_pred

array([2, 2, 0, ..., 0, 1, 0])

In [ ]:
Classification_Report_N = classification_report(y_test, y_pred)
print(Classification_Report_N)

              precision    recall  f1-score   support

           0       0.73      0.95      0.82       276
           1       0.92      0.83      0.87       276
           2       0.91      0.88      0.89       277
           3       0.93      0.79      0.85       276

    accuracy                           0.86      1105
   macro avg       0.87      0.86      0.86      1105
weighted avg       0.87      0.86      0.86      1105



In [ ]:
X_test[:5]
y_test[:5]
y_pred[:5]

12446    Shocking Video Of Officer Punching Woman Ignit...
3868     YOLO ATTACK: Birthday Stabbing Turns Party Int...
3301                             Great News For Obamacare 
11543    Katie Nolan Calls On Dallas Cowboys To Get Hel...
9501     Markets Tumble On Fears Of Global Economic Slo...
Name: text, dtype: object

In [ ]:
y_test[:5]

12446    2
3868     2
3301     0
11543    1
9501     0
Name: category_number, dtype: int64

In [ ]:
y_pred[:5]

array([2, 2, 0, 1, 0])

The above model was built without pre-processing

In [ ]:
balanced_data['preprocessed_text'] = balanced_data.text.apply(preprocess)

In [ ]:
final_balanced_data = balanced_data.drop(['preproces_stext'], axis=1)

In [ ]:
final_balanced_data

text  category  \
594    How to Develop the Next Generation of Innovato...  BUSINESS   
3093   Madoff Victims' Payout Nears $7.2 Billion, Tru...  BUSINESS   
7447   Bay Area Floats 'Sanctuary In Transit Policy' ...  BUSINESS   
10388  Microsoft Agrees To Acquire LinkedIn For $26.2...  BUSINESS   
1782    Inside A Legal, Multibillion Dollar Weed Market   BUSINESS   
...                                                  ...       ...   
9924   A Call for Data Literacy If we care about youn...   SCIENCE   
10219  Here's What Happens When Someone Sneezes On An...   SCIENCE   
11884  Most People Don't See How Climate Change Is Af...   SCIENCE   
7854   Watch Octopuses Meet for Blind Date, Tricky Se...   SCIENCE   
10191  The World Of Science Has A Lot To Look Forward...   SCIENCE   

       category_number                                  preprocessed_text  
594                  0  develop Generation Innovators stop treat way g...  
3093                 0  Madoff Victims Payout near $ 7.2 billion Trust...  
7447                 0  Bay Area Floats Sanctuary Transit Policy prote...  
10388                0  Microsoft agree acquire linkedin $ 26.2 billio...  
1782                 0       inside Legal Multibillion Dollar Weed Market  
...                ...                                                ...  
9924                 3  Data Literacy care young people privacy need t...  
10219                3                             happen sneeze Airplane  
11884                3  People climate change affect life Problem Heid...  
7854                 3  watch Octopuses meet Blind Date tricky Sex Feb...  
10191                3  World Science Lot look Forward 2016 conquest s...  

[5524 rows x 4 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(final_balanced_data.preprocessed_text, final_balanced_data.category_number, test_size= 0.2, random_state = 42, stratify = balanced_data.category_number)

In [ ]:
classifier_n = Pipeline([('vectorizer_bow,', CountVectorizer(ngram_range=(1,2))), ('Multi NB', MultinomialNB())])
classifier_n

Pipeline(steps=[('vectorizer_bow,', CountVectorizer(ngram_range=(1, 2))),
                ('Multi NB', MultinomialNB())])

In [ ]:
classifier_n.fit(X_train, y_train)

y_pred = classifier_n.predict(X_test)
y_pred

array([2, 2, 0, ..., 0, 1, 0])

In [ ]:
Classification_Report_N = classification_report(y_test, y_pred)
print(Classification_Report_N)

              precision    recall  f1-score   support

           0       0.83      0.90      0.86       276
           1       0.91      0.88      0.89       276
           2       0.89      0.94      0.91       277
           3       0.93      0.83      0.88       276

    accuracy                           0.89      1105
   macro avg       0.89      0.89      0.89      1105
weighted avg       0.89      0.89      0.89      1105



In [ ]:
'''TF-IDF'''

from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [ ]:
tf_idf = TfidfVectorizer()

In [ ]:
transformed_output = tf_idf.fit_transform(corpus)
transformed_output

<7x28 sparse matrix of type '<class 'numpy.float64'>'
	with 46 stored elements in Compressed Sparse Row format>

In [ ]:
tf_idf.vocabulary_

{'thor': 25,
 'eating': 10,
 'pizza': 22,
 'loki': 17,
 'is': 16,
 'ironman': 15,
 'ate': 7,
 'already': 0,
 'apple': 5,
 'announcing': 4,
 'new': 20,
 'iphone': 14,
 'tomorrow': 26,
 'tesla': 24,
 'model': 19,
 'google': 12,
 'pixel': 21,
 'microsoft': 18,
 'surface': 23,
 'amazon': 2,
 'eco': 11,
 'dot': 9,
 'am': 1,
 'biryani': 8,
 'and': 3,
 'you': 27,
 'are': 6,
 'grapes': 13}

In [ ]:
features = tf_idf.get_feature_names_out()
features

array(['already', 'am', 'amazon', 'and', 'announcing', 'apple', 'are',
       'ate', 'biryani', 'dot', 'eating', 'eco', 'google', 'grapes',
       'iphone', 'ironman', 'is', 'loki', 'microsoft', 'model', 'new',
       'pixel', 'pizza', 'surface', 'tesla', 'thor', 'tomorrow', 'you'],
      dtype=object)

In [ ]:
for word in features:
  index = tf_idf.vocabulary_.get(word)
  print(f"{word}",":", tf_idf.idf_[index])

already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891


In [ ]:
corpus[:2]

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [ ]:
transformed_output.toarray()[:2]

array([[0.24266547, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24266547, 0.        , 0.        ,
        0.40286636, 0.        , 0.        , 0.        , 0.        ,
        0.24266547, 0.11527033, 0.24266547, 0.        , 0.        ,
        0.        , 0.        , 0.72799642, 0.        , 0.        ,
        0.24266547, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.30652086,
        0.5680354 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5680354 ,
        0.        , 0.26982671, 0.        , 0.        , 0.        ,
        0.30652086, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30652086, 0.        ]])

In [ ]:
''''ECommerce_data'''

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv('/content/Ecommerce_data.csv')
df.head(10)

Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories
5  Selfie: How We Became So Self-Obsessed and Wha...                   Books
6  Quantum QHM8810 Keyboard with Mouse (Black) Ul...             Electronics
7  Y&S Uv Protected Non Polarized Wayfarer Boy's ...  Clothing & Accessories
8  HP external USB DVD Drive DVDRW DVD-ROM A2U56A...             Electronics
9  Fujifilm Instax Mini Monochrome Film (10 Sheet...                   Books

In [ ]:
df.label.value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [ ]:
df['label_number'] = df.label.map({'Household' : 0, 'Electronics' : 1, 'Clothing & Accessories' : 2, 'Books' : 3})
df

Text  \
0      Urban Ladder Eisner Low Back Study-Office Comp...   
1      Contrast living Wooden Decorative Box,Painted ...   
2      IO Crest SY-PCI40010 PCI RAID Host Controller ...   
3      ISAKAA Baby Socks from Just Born to 8 Years- P...   
4      Indira Designer Women's Art Mysore Silk Saree ...   
...                                                  ...   
23995                 Marvel Physics MCQ's for MHT - CET   
23996  Internet Download Manager | Lifetime License |...   
23997  Sadhubela's Handcrafted Iron Degchi Handi Pot ...   
23998  Audio-Technica AT-LP60 Automatic Belt Driven D...   
23999  LG GH24NSB0 DVD Writer 24X SATA Internal OEM P...   

                        label  label_number  
0                   Household             0  
1                   Household             0  
2                 Electronics             1  
3      Clothing & Accessories             2  
4      Clothing & Accessories             2  
...                       ...           ...  
23995                   Books             3  
23996                   Books             3  
23997               Household             0  
23998             Electronics             1  
23999             Electronics             1  

[24000 rows x 3 columns]

In [ ]:
'''Without Pre-processing'''

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Text, df.label_number, test_size= 0.2, random_state = 42, stratify = df.label_number)


In [ ]:
X_train.shape

(19200,)

In [ ]:
X_test.shape

(4800,)

In [ ]:
y_train.value_counts()

label_number
3    4800
2    4800
1    4800
0    4800
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

label_number
0    1200
1    1200
2    1200
3    1200
Name: count, dtype: int64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [ ]:
classifier = Pipeline([('tf_idf,', TfidfVectorizer()), ('knn', KNeighborsClassifier())])
classifier

Pipeline(steps=[('tf_idf,', TfidfVectorizer()),
                ('knn', KNeighborsClassifier())])

In [ ]:
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 2, ..., 1, 3, 1])

In [ ]:
Classification_Report = classification_report(y_test, y_pred)
print(Classification_Report)

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1200
           1       0.97      0.96      0.96      1200
           2       0.98      0.98      0.98      1200
           3       0.98      0.96      0.97      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800



In [ ]:
classifier_NB = Pipeline([('tf_idf,', TfidfVectorizer()), ('Multi NB', MultinomialNB())])
classifier_NB

Pipeline(steps=[('tf_idf,', TfidfVectorizer()), ('Multi NB', MultinomialNB())])

In [ ]:
classifier_NB.fit(X_train, y_train)

y_pred = classifier_NB.predict(X_test)
y_pred

array([0, 1, 2, ..., 1, 3, 1])

In [ ]:
Classification_Report_NB = classification_report(y_test, y_pred)
print(Classification_Report_NB)

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      1200
           1       0.97      0.97      0.97      1200
           2       0.98      0.98      0.98      1200
           3       0.99      0.94      0.96      1200

    accuracy                           0.96      4800
   macro avg       0.97      0.96      0.96      4800
weighted avg       0.97      0.96      0.96      4800



In [ ]:
X_test[:5]

10572    Deco Home Cotton Modern Arabesque Bedding, Kin...
23834    Sky Tech® High Speed External Memory Card Read...
13988    Allen Solly Men's Cotton Handkerchief Navy/Sky...
10777    Samriddhi Artificial Leaves Garlands/Creepers ...
11896    Seagate 2TB Backup Plus Slim (Blue) USB 3.0 Ex...
Name: Text, dtype: object

In [ ]:
y_test[:5]

10572    0
23834    1
13988    2
10777    0
11896    1
Name: label_number, dtype: int64

In [ ]:
y_pred[:5]

array([0, 1, 2, 0, 1])

In [ ]:
classifier_RF = Pipeline([('tf_idf,', TfidfVectorizer()), ('kRandom forestnn', RandomForestClassifier())])
classifier_RF

Pipeline(steps=[('tf_idf,', TfidfVectorizer()),
                ('kRandom forestnn', RandomForestClassifier())])

In [ ]:
classifier_RF.fit(X_train, y_train)

y_pred = classifier_RF.predict(X_test)
y_pred

array([0, 1, 2, ..., 1, 3, 1])

In [ ]:
Classification_Report_RF = classification_report(y_test, y_pred)
print(Classification_Report_RF)

              precision    recall  f1-score   support

           0       0.96      0.97      0.96      1200
           1       0.98      0.97      0.98      1200
           2       0.98      0.98      0.98      1200
           3       0.98      0.98      0.98      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800



In [ ]:
'''Using Preprocessing'''


import spacy

nlp = spacy.load("en_core_web_sm")

#Function to remove stop words
def preprocess_no_stop_words(text):
  doc = nlp(text)

  no_StopWords = [token.text for token in doc if not token.is_stop and not token.is_punct]
  return " ".join(no_StopWords)

In [ ]:
df['preprocessed_text'] = df['Text'].apply(preprocess_no_stop_words)
df.head(10)

Text                   label  \
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household   
1  Contrast living Wooden Decorative Box,Painted ...               Household   
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics   
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories   
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories   
5  Selfie: How We Became So Self-Obsessed and Wha...                   Books   
6  Quantum QHM8810 Keyboard with Mouse (Black) Ul...             Electronics   
7  Y&S Uv Protected Non Polarized Wayfarer Boy's ...  Clothing & Accessories   
8  HP external USB DVD Drive DVDRW DVD-ROM A2U56A...             Electronics   
9  Fujifilm Instax Mini Monochrome Film (10 Sheet...                   Books   

   label_number                                  preprocessed_text  
0             0  Urban Ladder Eisner Low Study Office Computer ...  
1             0  Contrast living Wooden Decorative Box Painted ...  
2             1  IO Crest SY PCI40010 PCI RAID Host Controller ...  
3             2  ISAKAA Baby Socks Born 8 Years- Pack 4 6 8 12 ...  
4             2  Indira Designer Women Art Mysore Silk Saree Bl...  
5             3                               Selfie Self Obsessed  
6             1  Quantum QHM8810 Keyboard Mouse Black Ultra sli...  
7             2  Y&S Uv Protected Non Polarized Wayfarer Boy Gi...  
8             1  HP external USB DVD Drive DVDRW DVD ROM A2U56A...  
9             3  Fujifilm Instax Mini Monochrome Film 10 Sheets...

In [ ]:
df['Text'][0]

'Urban Ladder Eisner Low Back Study-Office Computer Chair(Black) A study in simple. The Eisner study chair has a firm foam cushion, which makes long hours at your desk comfortable. The flexible meshed back is designed for air-circulation and support when you lean back. The curved arms provide ergonomic forearm support. Adjust the height using the gas lift to find that comfortable position and the nylon castors make it easy to move around your space. Chrome legs refer to the images for dimension details any assembly required will be done by the UL team at the time of delivery indoor use only.'

In [ ]:
df['preprocessed_text'][0]

'Urban Ladder Eisner Low Study Office Computer Chair(Black study simple Eisner study chair firm foam cushion makes long hours desk comfortable flexible meshed designed air circulation support lean curved arms provide ergonomic forearm support Adjust height gas lift find comfortable position nylon castors easy space Chrome legs refer images dimension details assembly required UL team time delivery indoor use'

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.preprocessed_text, df.label_number, test_size= 0.2, random_state = 42, stratify = df.label_number)


In [ ]:
classifier_RF = Pipeline([('tf_idf,', TfidfVectorizer()), ('knn', RandomForestClassifier())])
classifier_RF

Pipeline(steps=[('tf_idf,', TfidfVectorizer()),
                ('knn', RandomForestClassifier())])

In [ ]:
classifier_RF.fit(X_train, y_train)

y_pred = classifier_RF.predict(X_test)
y_pred

array([0, 1, 2, ..., 1, 3, 1])

In [ ]:
Classification_Report_RF = classification_report(y_test, y_pred)
print(Classification_Report_RF)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1200
           1       0.98      0.97      0.98      1200
           2       0.98      0.98      0.98      1200
           3       0.98      0.98      0.98      1200

    accuracy                           0.98      4800
   macro avg       0.98      0.98      0.98      4800
weighted avg       0.98      0.98      0.98      4800

